[train_info]
; 12306乘车人姓名，如张三
person = 张三
; 始发站
fromstation = 北京
; 终点站
destination = 郑州
; 出发日期，格式为年-月-日 如：0000-00-00
train_date = 2025-07-10
; 列车号，如：K2188
train_number = K2188
; 定义座位类型： 1为硬座 3为硬卧 4 为软卧
zw = 1
; 是否学生票： 0为否，1为是
student_ = 0
; 是否接受无座：0为接受，1为不接受
wuzuo = 1